### ISSUE TITLE
BD.Cheats.Crafting.AddAll() not working only adds clothes

### ISSUE THREAD

**Issue by Maxilos9999** [WolvenKit/BraindanceProtocol#25]
This command only adds a few things for me not everything.  I only have 1 type of grenade still and according to my research there should be multiple types to craft.

**Comment by osulli** [comment]
Please could you share the results of your research and let us know, or better yet contribute the code, to add the missing times?

**Comment by Kyle873** [comment]
Ideally we should be pulling all the hashes at runtime instead of from a static hash list in a file. I am very aware that our current list is incomplete and is missing several recipes that don't have a string ID as seen by research into the TDB. For now, I will incorporate a temporary hex list courtesy of gibbed until this has been done to fill in the missing gaps.

**Comment by osulli** [comment]
Solved by #30
